spring.application.name=med
# ===============================
# DATABASE CONFIGURATION
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/association_med_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# ===============================
# SERVER
# ===============================

server.port=8080

# ===============================
# config Email notifs
# ===============================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pfe2475@gmail.com
spring.mail.password=acpb rcjo awwr ithx

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
