spring.application.name=med
# ===============================
# DATABASE CONFIGURATION
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/association_med_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# ===============================
# SERVER
# ===============================

server.port=8080

# ===============================
# config Email notifs
# ===============================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ambbengardane@gmail.com
spring.mail.password=qnii lmxj oozb djbe

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# Security
# ===============================

jwt.secret=ROi1WAwqF/+cOrlLBoCJsODIWgLfErrmuelf4v7Cjs4=


# ===============================
# ERRORS DETAIL (IMPORTANT)
# ===============================
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always

# ===============================
# SPRING LOGS (DEBUG)
# ===============================
logging.level.org.springframework=INFO
logging.level.org.springframework.orm.jpa=DEBUG

# ===============================
# Dossier images
# ===============================

file.upload-dir=uploads
